version: "3.9"  # optional since v1.27.0

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://admin:12345@postgres/test?sslmode=disable
    depends_on:
      - postgres
  migrations:
    image: migrate/migrate
    command: -database postgres://admin:12345@postgres/test?sslmode=disable -path=/migrations/ up
    volumes:
      - ./migrations/:/migrations
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data-binaryx:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
      POSTGRES_HOST: localhost
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 40
    volumes:
      - pg-admin-data-binaryx:/var/lib/pgadmin

volumes:
  pg-data-binaryx: {}
  pg-admin-data-binaryx: {}
